apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vclusters
spec: {}
status: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vcluster1
  namespace: vclusters
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vcluster1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vcluster1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster1
  namespace: vclusters
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: null
      repo: null
      version: null
    values: |-
      service:
        type: NodePort
      syncer:
        extraArgs:
          - --tls-san=bobymcbobs.pair.sharing.io
  kubernetesVersion: 1.23.4
